// <auto-generated />
namespace Makeup2.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Userx : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Userx));
        
        string IMigrationMetadata.Id
        {
            get { return "202101150254112_Userx"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
